

import { Translation, Vehicle, Reservation, Review, Expense, Tour } from './types';

// Placeholder logo that matches the described Red/Silver circular design. 
// Replace this URL with the actual URL of your hosted image.
export const COMPANY_LOGO = "https://placehold.co/200x200/dc2626/ffffff?text=AV&font=roboto";

export const EXTRAS_PRICING = {
  gps: 500,
  childSeat: 1000,
  insurance: 2500,
  delivery: 2000,
};

export const TRANSLATIONS: Record<string, Translation> = {
  pt: {
    nav: {
      home: 'Início',
      fleet: 'Frota',
      tours: 'Tours',
      admin: 'Administração',
      login: 'Entrar',
      logout: 'Sair',
      my_reservations: 'Minhas Reservas',
      welcome: 'Olá',
    },
    hero: {
      title: 'Alugue o carro perfeito para sua jornada',
      subtitle: 'Entrega em domicílio, preços transparentes e reservas simplificadas.',
      search_placeholder: 'Local de retirada (ex: Praia)',
      search_btn: 'Buscar Disponibilidade',
      pickup_date: 'Data Retirada',
      dropoff_date: 'Data Devolução',
      error_dates: 'Selecione datas válidas',
    },
    filters: {
      all: 'Todos',
      economy: 'Económico',
      suv: 'SUV',
      luxury: 'Luxo',
      automatic: 'Automático',
      manual: 'Manual',
      van: 'Van',
    },
    vehicle: {
      day: 'dia',
      seats: 'lugares',
      book_now: 'Reservar Agora',
      unavailable: 'Indisponível (Datas)',
      reviews: 'avaliações',
      maintenance: 'Manutenção',
    },
    booking: {
      title: 'Finalizar Reserva',
      step_details: 'Detalhes',
      step_extras: 'Extras',
      step_docs: 'Documentos',
      step_payment: 'Pagamento',
      total: 'Total',
      discount_applied: 'Desconto (>7 dias)',
      pay_now: 'A pagar agora (Depósito)',
      pay_later: 'A pagar ao balcão',
      delivery_opt: 'Receber em casa (+2000 CVE)',
      delivery_placeholder: 'Endereço de entrega...',
      upload_id: 'Carregar BI / Passaporte',
      upload_license: 'Carregar Carta de Condução',
      upload_success: 'Arquivo recebido',
      confirm_pay: 'Pagar e Confirmar',
      payment_method: 'Método de Pagamento',
      pay_vinti4: 'Rede Vinti4 (Débito Local)',
      pay_card: 'Cartão de Crédito (Genérico)',
      pay_stripe: 'Cartão de Crédito (Stripe)',
      pay_paypal: 'PayPal',
      success_title: 'Reserva Confirmada!',
      success_msg: 'Seu pagamento foi processado com sucesso.',
      download_contract: 'Baixar Contrato',
      close: 'Fechar',
      reviews_title: 'Avaliações',
      no_reviews: 'Sem avaliações.',
      write_review: 'Avaliar',
      submit_review: 'Enviar',
      your_rating: 'Sua Nota',
      your_comment: 'Comentário',
      extras_title: 'Adicionar Extras',
      extra_gps: 'GPS (+500/dia)',
      extra_child_seat: 'Cadeira Criança (+1000/dia)',
      extra_insurance: 'Seguro Total (+2500/dia)',
      error_dates_invalid: 'Data final deve ser após data inicial',
      about_company_title: 'Sobre esta empresa',
      about_company_desc: 'Ao reservar conosco está a suportar o comércio local de Cabo Verde.',
      useful_info_title: 'Informação útil',
      info_cancellation: 'Cancelamento gratuito até 24h',
      info_no_credit_card: 'Não é necessário cartão de crédito',
      info_insurance: 'Cobertura de danos com franquia (CDW)',
      info_deposit: 'Caução no levantamento',
      pickup_location_title: 'Ponto de levantamento',
      loc_airport: 'Aeroporto (RAI)',
      loc_city: 'Escritório Centro Cidade',
      loc_port: 'Terminal Marítimo',
      loc_custom: 'Outra Localização',
      free: 'Grátis',
      flight_number: 'Número do Voo',
      flight_hint: 'Se o voo atrasar, saberemos.',
      num_passengers: 'Número de pessoas',
      payment_processing: 'Processando pagamento...',
      payment_success: 'Pagamento aprovado!',
      card_holder: 'Nome no Cartão',
      card_number: 'Número do Cartão',
      card_expiry: 'Validade (MM/AA)',
      card_cvc: 'CVC',
      vinti4_phone: 'Telemóvel (ex: 9911234)',
      vinti4_instr: 'Você receberá uma notificação no seu telemóvel para confirmar o pagamento.',
      stripe_instr: 'Pagamento seguro processado via Stripe.',
      paypal_instr: 'Você será redirecionado para o PayPal para completar sua compra.',
    },
    tour_booking: {
      title: 'Comprar Pacote de Tour',
      select_date: 'Data do Passeio',
      guests: 'Número de Pessoas',
      total_price: 'Preço Total',
      confirm_purchase: 'Confirmar Compra',
      success_title: 'Compra Realizada com Sucesso!',
      success_msg: 'Seu tour foi agendado. Prepare-se para a aventura!',
      email_sent: 'Um e-mail de confirmação foi enviado para',
      download_ticket: 'Baixar Voucher',
    },
    tours: {
      title: 'Experiências em Santiago',
      subtitle: 'Descubra a ilha com nossos pacotes exclusivos com motorista ou self-drive.',
      book_tour: 'Ver Frota Disponível',
      duration: 'Duração',
      included: 'Inclui',
      view_details: 'Ver Detalhes',
      buy_now: 'Comprar Pacote',
    },
    admin: {
      dashboard: 'Painel Admin',
      revenue: 'Receita Mensal',
      active_rentals: 'Em Circulação',
      fleet_status: 'Status da Frota',
      recent_reservations: 'Reservas Recentes',
      reviews_moderation: 'Moderação',
      approve: 'Aprovar',
      reject: 'Rejeitar',
      status: 'Status',
      tabs_overview: 'Visão Geral',
      tabs_fleet: 'Frota',
      tabs_reservations: 'Reservas',
      tabs_deliveries: 'Entregas',
      tabs_reviews: 'Avaliações',
      tabs_settings: 'Configurações',
      tabs_finance: 'Financeiro',
      tabs_tours: 'Tours',
      tabs_reports: 'Relatórios',
      filter_pending: 'Pendentes',
      filter_all: 'Todos',
      add_vehicle: 'Adicionar Veículo',
      add_tour: 'Adicionar Tour',
      edit: 'Editar',
      delete: 'Excluir',
      plate: 'Matrícula',
      price: 'Preço/Dia',
      actions: 'Ações',
      save: 'Salvar',
      cancel: 'Cancelar',
      mark_active: 'Entregar (Check-out)',
      mark_completed: 'Devolver (Check-in)',
      mark_cancelled: 'Cancelar',
      confirm: 'Confirmar',
      confirm_delete: 'Tem certeza que deseja excluir este veículo?',
      api_key_label: 'Chave da API Geral (Mapas, etc)',
      api_key_placeholder: 'Insira sua chave de API aqui...',
      vinti4_section: 'Integração Rede Vinti4',
      vinti4_pos_id: 'ID do POS (Vinti4)',
      vinti4_api_key: 'Token de Autenticação (Vinti4)',
      vinti4_doc_link: 'Ver documentação oficial Vinti4',
      stripe_section: 'Integração Stripe',
      stripe_key: 'Chave Pública (Publishable Key)',
      paypal_section: 'Integração PayPal',
      paypal_client: 'Client ID',
      save_settings: 'Salvar Configurações',
      settings_saved: 'Configurações salvas com sucesso!',
      payment_status: 'Pagamento',
      paid: 'Pago',
      pending_payment: 'Pendente',
      fin_total_income: 'Receita Total',
      fin_total_expenses: 'Despesas Totais',
      fin_net_profit: 'Lucro Líquido',
      fin_add_expense: 'Nova Despesa',
      fin_desc: 'Descrição',
      fin_amount: 'Valor (CVE)',
      fin_category: 'Categoria',
      fin_date: 'Data',
      fin_recent_transactions: 'Transações Recentes',
      fin_type_income: 'Receita (Reserva)',
      fin_type_expense: 'Despesa',
      // Settings sub-tabs
      settings_general: 'Dados da Empresa',
      settings_integrations: 'Integrações',
      settings_payments: 'Pagamentos',
      comp_name: 'Nome da Empresa',
      comp_email: 'Email de Contato',
      comp_phone: 'Telefone',
      comp_address: 'Endereço Físico',
      // Tours
      tour_title: 'Título',
      tour_price: 'Preço',
      tour_features: 'Destaques',
      tour_features_help: 'Separados por vírgula',
      // Reports
      rep_occupancy: 'Taxa de Ocupação',
      rep_avg_ticket: 'Ticket Médio',
      rep_rev_by_cat: 'Receita por Categoria',
      rep_monthly_growth: 'Crescimento Mensal',
      rep_export_csv: 'Exportar CSV',
      rep_export_pdf: 'Exportar PDF',
      rep_statement: 'Demonstrativo Financeiro (DRE)',
      rep_avg_duration: 'Duração Média (Dias)',
      rep_days_rented: 'Total Dias Alugados',
      rep_status_dist: 'Distribuição por Status',
      rep_vehicle_perf: 'Desempenho da Frota',
      rep_top_vehicles: 'Top 5 Veículos (Receita)',
      rep_perf_days: 'Dias Alugados',
      rep_perf_revenue: 'Receita Total',
      // Filters
      rep_filter_date_start: 'Data Início',
      rep_filter_date_end: 'Data Fim',
      rep_filter_vehicle: 'Veículo',
      rep_filter_category: 'Categoria',
      rep_filter_type: 'Tipo de Transação',
      rep_filter_clear: 'Limpar Filtros',
      rep_filter_apply: 'Aplicar',
    },
    customer: {
      dashboard: 'Minhas Reservas',
      status: 'Status',
      leave_review: 'Avaliar',
      review_submitted: 'Enviada',
      download_contract: 'Contrato',
      cancel_booking: 'Cancelar',
      confirm_cancel: 'Tem certeza que deseja cancelar esta reserva? (Grátis se faltar mais de 48h)',
      tabs_reservations: 'Minhas Reservas',
      tabs_profile: 'Configurações de Perfil',
      profile_settings: 'Editar Perfil',
      personal_details: 'Dados Pessoais',
      save_changes: 'Salvar Alterações',
      profile_updated: 'Perfil atualizado com sucesso!',
    },
    auth: {
      login_title: 'Acessar Conta',
      login_admin: 'Entrar como Admin',
      login_customer: 'Entrar como Cliente',
      email: 'Email',
      password: 'Senha',
    },
    footer: {
      about: 'Sobre Nós',
      about_text: 'A Auto Vicente oferece a melhor experiência de aluguel de carros em Cabo Verde. Segurança, conforto e suporte 24h.',
      links: 'Links Rápidos',
      contact: 'Contacto',
      address: 'Achada Santo António, Praia, Cabo Verde',
      phone: '+238 991 12 34',
      email: 'reservas@autovicente.cv',
      rights: 'Todos os direitos reservados.',
      privacy: 'Privacidade',
      terms: 'Termos',
    },
    pagination: {
      prev: 'Anterior',
      next: 'Próximo',
      page: 'Página',
      of: 'de',
    },
  },
  en: {
    nav: {
      home: 'Home',
      fleet: 'Fleet',
      tours: 'Tours',
      admin: 'Admin',
      login: 'Login',
      logout: 'Logout',
      my_reservations: 'My Reservations',
      welcome: 'Hello',
    },
    hero: {
      title: 'Rent the perfect car for your journey',
      subtitle: 'Home delivery, transparent pricing, and simple booking.',
      search_placeholder: 'Pickup location (e.g. Praia)',
      search_btn: 'Search Availability',
      pickup_date: 'Pickup Date',
      dropoff_date: 'Dropoff Date',
      error_dates: 'Select valid dates',
    },
    filters: {
      all: 'All',
      economy: 'Economy',
      suv: 'SUV',
      luxury: 'Luxury',
      automatic: 'Automatic',
      manual: 'Manual',
      van: 'Van',
    },
    vehicle: {
      day: 'day',
      seats: 'seats',
      book_now: 'Book Now',
      unavailable: 'Unavailable (Dates)',
      reviews: 'reviews',
      maintenance: 'Maintenance',
    },
    booking: {
      title: 'Complete Reservation',
      step_details: 'Details',
      step_extras: 'Extras',
      step_docs: 'Documents',
      step_payment: 'Payment',
      total: 'Total Amount',
      discount_applied: 'Discount (>7 days)',
      pay_now: 'Pay Now (Deposit)',
      pay_later: 'Pay at Counter',
      delivery_opt: 'Deliver to location (+2000 CVE)',
      delivery_placeholder: 'Delivery address...',
      upload_id: 'Upload ID / Passport',
      upload_license: 'Upload Driver License',
      upload_success: 'File received',
      confirm_pay: 'Pay & Confirm',
      payment_method: 'Payment Method',
      pay_vinti4: 'Vinti4 Network (Local Debit)',
      pay_card: 'Credit Card (Generic)',
      pay_stripe: 'Credit Card (Stripe)',
      pay_paypal: 'PayPal',
      success_title: 'Reservation Confirmed!',
      success_msg: 'Your payment was processed successfully.',
      download_contract: 'Download Contract',
      close: 'Close',
      reviews_title: 'Reviews',
      no_reviews: 'No reviews yet.',
      write_review: 'Rate Vehicle',
      submit_review: 'Submit Review',
      your_rating: 'Your Rating',
      your_comment: 'Your Comment',
      extras_title: 'Add Extras',
      extra_gps: 'GPS (+500/day)',
      extra_child_seat: 'Child Seat (+1000/day)',
      extra_insurance: 'Full Insurance (+2500/day)',
      error_dates_invalid: 'End date must be after start date',
      about_company_title: 'About this company',
      about_company_desc: 'By booking with us you are supporting local Cape Verdean commerce.',
      useful_info_title: 'Useful Information',
      info_cancellation: 'Free cancellation up to 24h',
      info_no_credit_card: 'No credit card required',
      info_insurance: 'Damage coverage with deductible (CDW)',
      info_deposit: 'Security deposit on pickup',
      pickup_location_title: 'Pickup Location',
      loc_airport: 'Airport (RAI)',
      loc_city: 'City Center Office',
      loc_port: 'Maritime Terminal',
      loc_custom: 'Other Location',
      free: 'Free',
      flight_number: 'Flight Number',
      flight_hint: 'So we know if your flight is delayed.',
      num_passengers: 'Number of people',
      payment_processing: 'Processing payment...',
      payment_success: 'Payment approved!',
      card_holder: 'Cardholder Name',
      card_number: 'Card Number',
      card_expiry: 'Expiry (MM/YY)',
      card_cvc: 'CVC',
      vinti4_phone: 'Mobile Number (e.g. 9911234)',
      vinti4_instr: 'You will receive a push notification on your phone to confirm the payment.',
      stripe_instr: 'Secure payment processed via Stripe.',
      paypal_instr: 'You will be redirected to PayPal to complete your purchase.',
    },
    tour_booking: {
      title: 'Buy Tour Package',
      select_date: 'Tour Date',
      guests: 'Number of Guests',
      total_price: 'Total Price',
      confirm_purchase: 'Confirm Purchase',
      success_title: 'Purchase Successful!',
      success_msg: 'Your tour has been scheduled. Get ready for the adventure!',
      email_sent: 'A confirmation email has been sent to',
      download_ticket: 'Download Voucher',
    },
    tours: {
      title: 'Santiago Experiences',
      subtitle: 'Discover the island with our exclusive driver or self-drive packages.',
      book_tour: 'See Available Fleet',
      duration: 'Duration',
      included: 'Included',
      view_details: 'View Details',
      buy_now: 'Buy Package',
    },
    admin: {
      dashboard: 'Dashboard',
      revenue: 'Monthly Revenue',
      active_rentals: 'On Road',
      fleet_status: 'Fleet Status',
      recent_reservations: 'Recent Reservations',
      reviews_moderation: 'Review Moderation',
      approve: 'Approve',
      reject: 'Reject',
      status: 'Status',
      tabs_overview: 'Overview',
      tabs_fleet: 'Fleet Management',
      tabs_reservations: 'Reservations',
      tabs_deliveries: 'Deliveries',
      tabs_reviews: 'Reviews',
      tabs_settings: 'Settings',
      tabs_finance: 'Finance',
      tabs_tours: 'Tours',
      tabs_reports: 'Reports',
      filter_pending: 'Pending',
      filter_all: 'All',
      add_vehicle: 'Add Vehicle',
      add_tour: 'Add Tour',
      edit: 'Edit',
      delete: 'Delete',
      plate: 'Plate',
      price: 'Price/Day',
      actions: 'Actions',
      save: 'Save',
      cancel: 'Cancel',
      mark_active: 'Dispatch (Check-out)',
      mark_completed: 'Return (Check-in)',
      mark_cancelled: 'Cancel',
      confirm: 'Confirm',
      confirm_delete: 'Are you sure you want to delete this vehicle?',
      api_key_label: 'General API Key (Maps, etc)',
      api_key_placeholder: 'Enter your API key here...',
      vinti4_section: 'Vinti4 Network Integration',
      vinti4_pos_id: 'POS ID (Vinti4)',
      vinti4_api_key: 'Authentication Token (Vinti4)',
      vinti4_doc_link: 'View official Vinti4 documentation',
      stripe_section: 'Stripe Integration',
      stripe_key: 'Public Key (Publishable Key)',
      paypal_section: 'PayPal Integration',
      paypal_client: 'Client ID',
      save_settings: 'Save Settings',
      settings_saved: 'Settings saved successfully!',
      payment_status: 'Payment',
      paid: 'Paid',
      pending_payment: 'Pending',
      fin_total_income: 'Total Revenue',
      fin_total_expenses: 'Total Expenses',
      fin_net_profit: 'Net Profit',
      fin_add_expense: 'Add Expense',
      fin_desc: 'Description',
      fin_amount: 'Amount (CVE)',
      fin_category: 'Category',
      fin_date: 'Date',
      fin_recent_transactions: 'Recent Transactions',
      fin_type_income: 'Income (Reservation)',
      fin_type_expense: 'Expense',
      // Settings sub-tabs
      settings_general: 'Company Details',
      settings_integrations: 'Integrations',
      settings_payments: 'Payments',
      comp_name: 'Company Name',
      comp_email: 'Contact Email',
      comp_phone: 'Phone Number',
      comp_address: 'Physical Address',
      // Tours
      tour_title: 'Title',
      tour_price: 'Price',
      tour_features: 'Features',
      tour_features_help: 'Comma separated',
      // Reports
      rep_occupancy: 'Occupancy Rate',
      rep_avg_ticket: 'Average Ticket',
      rep_rev_by_cat: 'Revenue by Category',
      rep_monthly_growth: 'Monthly Growth',
      rep_export_csv: 'Export CSV',
      rep_export_pdf: 'Export PDF',
      rep_statement: 'Financial Statement',
      rep_avg_duration: 'Avg Duration (Days)',
      rep_days_rented: 'Total Days Rented',
      rep_status_dist: 'Status Distribution',
      rep_vehicle_perf: 'Fleet Performance',
      rep_top_vehicles: 'Top 5 Vehicles (Revenue)',
      rep_perf_days: 'Days Rented',
      rep_perf_revenue: 'Total Revenue',
      // Filters
      rep_filter_date_start: 'Start Date',
      rep_filter_date_end: 'End Date',
      rep_filter_vehicle: 'Vehicle',
      rep_filter_category: 'Category',
      rep_filter_type: 'Transaction Type',
      rep_filter_clear: 'Clear Filters',
      rep_filter_apply: 'Apply',
    },
    customer: {
      dashboard: 'My Reservations',
      status: 'Status',
      leave_review: 'Leave a Review',
      review_submitted: 'Review Submitted',
      download_contract: 'Contract',
      cancel_booking: 'Cancel Booking',
      confirm_cancel: 'Are you sure you want to cancel this reservation? (Free cancellation if >48h)',
      tabs_reservations: 'My Reservations',
      tabs_profile: 'Profile Settings',
      profile_settings: 'Edit Profile',
      personal_details: 'Personal Details',
      save_changes: 'Save Changes',
      profile_updated: 'Profile updated successfully!',
    },
    auth: {
      login_title: 'Login',
      login_admin: 'Login as Admin',
      login_customer: 'Login as Customer',
      email: 'Email',
      password: 'Password',
    },
    footer: {
      about: 'About Us',
      about_text: 'Auto Vicente offers the best car rental experience in Cape Verde. Safety, comfort and 24h support.',
      links: 'Quick Links',
      contact: 'Contact',
      address: 'Achada Santo António, Praia, Cape Verde',
      phone: '+238 991 12 34',
      email: 'reservas@autovicente.cv',
      rights: 'All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
    },
    pagination: {
      prev: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
    },
  },
};

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: '1',
    make: 'Renault',
    model: 'Kwid',
    year: 2023,
    category: 'economy',
    transmission: 'manual',
    seats: 4,
    pricePerDay: 3500,
    image: 'https://picsum.photos/id/1071/400/250',
    available: true,
    status: 'available',
    rating: 4.5,
    reviewCount: 12,
    plate: 'ST-23-45',
  },
  {
    id: '2',
    make: 'Toyota',
    model: 'Hilux',
    year: 2022,
    category: 'suv',
    transmission: 'manual',
    seats: 5,
    pricePerDay: 9000,
    image: 'https://picsum.photos/id/133/400/250',
    available: true,
    status: 'available',
    rating: 4.8,
    reviewCount: 28,
    plate: 'PR-99-01',
  },
  {
    id: '3',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2024,
    category: 'suv',
    transmission: 'automatic',
    seats: 5,
    pricePerDay: 7500,
    image: 'https://picsum.photos/id/29/400/250',
    available: true,
    status: 'available',
    rating: 4.7,
    reviewCount: 8,
    plate: 'ST-11-22',
  },
  {
    id: '4',
    make: 'Mercedes',
    model: 'C-Class',
    year: 2021,
    category: 'luxury',
    transmission: 'automatic',
    seats: 5,
    pricePerDay: 15000,
    image: 'https://picsum.photos/id/111/400/250',
    available: false,
    status: 'rented',
    rating: 5.0,
    reviewCount: 5,
    plate: 'SV-00-07',
  },
  {
    id: '5',
    make: 'Fiat',
    model: 'Panda',
    year: 2020,
    category: 'economy',
    transmission: 'manual',
    seats: 4,
    pricePerDay: 3000,
    image: 'https://picsum.photos/id/183/400/250',
    available: true,
    status: 'available',
    rating: 4.2,
    reviewCount: 15,
    plate: 'ST-55-88',
  },
  {
    id: '6',
    make: 'Kia',
    model: 'Carnival',
    year: 2023,
    category: 'van',
    transmission: 'automatic',
    seats: 7,
    pricePerDay: 12000,
    image: 'https://picsum.photos/id/85/400/250',
    available: false,
    status: 'maintenance',
    rating: 4.9,
    reviewCount: 3,
    plate: 'PR-88-11',
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'RES-001',
    vehicleId: '4',
    type: 'vehicle',
    userId: 'user-001',
    customerName: 'João Silva',
    startDate: '2023-11-01',
    endDate: '2023-11-05',
    status: 'active', // Currently out
    total: 45000,
    pickupType: 'office',
    extras: { gps: false, childSeat: false, insurance: true },
    paymentMethod: 'card',
    paymentStatus: 'paid',
    transactionId: 'tx_123456789',
    dateCreated: '2023-10-28',
  },
  {
    id: 'RES-002',
    vehicleId: '2',
    type: 'vehicle',
    userId: 'user-002',
    customerName: 'Maria Santos',
    startDate: '2023-11-10',
    endDate: '2023-11-12',
    status: 'pending',
    total: 45000,
    pickupType: 'delivery',
    pickupAddress: 'Hotel Pestana Tropico',
    extras: { gps: true, childSeat: false, insurance: false },
    paymentMethod: 'vinti4',
    paymentStatus: 'pending',
    dateCreated: '2023-11-01',
  },
  {
    id: 'RES-003',
    vehicleId: '1',
    type: 'vehicle',
    userId: 'user-001',
    customerName: 'João Silva',
    startDate: '2023-09-01',
    endDate: '2023-09-05',
    status: 'completed',
    total: 17500,
    pickupType: 'office',
    extras: { gps: false, childSeat: false, insurance: false },
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    dateCreated: '2023-08-25',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'REV-001',
    vehicleId: '1',
    customerName: 'Carlos Andrade',
    rating: 5,
    comment: 'Great little car for the city. Very economical!',
    date: '2023-09-10',
    status: 'approved',
  },
  {
    id: 'REV-002',
    vehicleId: '2',
    customerName: 'James Wilson',
    rating: 4,
    comment: 'Strong pickup, handled the dirt roads well. A bit noisy on highway.',
    date: '2023-09-15',
    status: 'approved',
  },
  {
    id: 'REV-003',
    vehicleId: '1',
    customerName: 'Ana Pereira',
    rating: 2,
    comment: 'Car was dirty when picked up.',
    date: '2023-10-01',
    status: 'pending',
  },
  {
    id: 'REV-004',
    vehicleId: '3',
    customerName: 'Sarah Smith',
    rating: 5,
    comment: 'Luxury feel for a good price. Loved the AC.',
    date: '2023-10-05',
    status: 'approved',
  },
];

export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'EXP-001',
    description: 'Vehicle Maintenance - Hilux PR-99-01',
    amount: 15000,
    category: 'maintenance',
    date: '2023-10-15',
  },
  {
    id: 'EXP-002',
    description: 'Fuel Refill (Fleet)',
    amount: 8500,
    category: 'fuel',
    date: '2023-10-20',
  },
  {
    id: 'EXP-003',
    description: 'Office Internet & Utilities',
    amount: 12000,
    category: 'office',
    date: '2023-11-01',
  },
  {
    id: 'EXP-004',
    description: 'Marketing Facebook Ads',
    amount: 5000,
    category: 'marketing',
    date: '2023-11-05',
  },
];

export const MOCK_TOURS: Tour[] = [
  {
    id: 'TOUR-001',
    title: 'Volta à Ilha Completa',
    description: 'Descubra as maravilhas de Santiago num dia. Passagem por Assomada, Tarrafal, Serra Malagueta e Calheta.',
    image: 'https://images.unsplash.com/photo-1596395819057-d37e29b1284c?q=80&w=800&auto=format&fit=crop',
    duration: '8 Horas (Full Day)',
    price: 12000,
    features: ['Guia Local', 'Almoço Típico', 'Pick-up Hotel'],
  },
  {
    id: 'TOUR-002',
    title: 'Cidade Velha Histórica',
    description: 'Visite o berço da nação cabo-verdiana, Património Mundial da UNESCO. Fortaleza Real e Rua Banana.',
    image: 'https://images.unsplash.com/photo-1620327315357-1950d8774775?q=80&w=800&auto=format&fit=crop',
    duration: '4 Horas (Half Day)',
    price: 6000,
    features: ['Entrada Fortaleza', 'Degustação Grogue', 'História'],
  },
  {
    id: 'TOUR-003',
    title: 'Relax em Tarrafal',
    description: 'Transporte direto para a praia mais bonita da ilha. Tempo livre para nadar e relaxar.',
    image: 'https://images.unsplash.com/photo-1544645224-b5a75971a858?q=80&w=800&auto=format&fit=crop',
    duration: '6 Horas',
    price: 9000,
    features: ['Transfer Privado', 'Cadeira Praia', 'Bebidas'],
  }
];