

import { Translation, Vehicle, Reservation, Review, Expense, Tour, CategoryItem, Driver } from './types';

// Placeholder logo that matches the described Red/Silver circular design. 
// Replace this URL with the actual URL of your hosted image.
export const COMPANY_LOGO = "https://placehold.co/200x200/dc2626/ffffff?text=AV&font=roboto";

export const MAINTENANCE_BUFFER_DAYS = 1; // Global setting for cleaning buffer

export const EXTRAS_PRICING = {
  gps: 500,
  childSeat: 1000,
  insurance: 2500,
  delivery: 2000,
};

export const DEFAULT_VEHICLE_CATEGORIES: CategoryItem[] = [
  { id: 'economy', name: 'Economy', type: 'vehicle' },
  { id: 'suv', name: 'SUV', type: 'vehicle' },
  { id: 'luxury', name: 'Luxury', type: 'vehicle' },
  { id: 'van', name: 'Van', type: 'vehicle' }
];

export const DEFAULT_EXPENSE_CATEGORIES: CategoryItem[] = [
  { id: 'maintenance', name: 'Maintenance', type: 'expense' },
  { id: 'fuel', name: 'Fuel', type: 'expense' },
  { id: 'office', name: 'Office', type: 'expense' },
  { id: 'marketing', name: 'Marketing', type: 'expense' },
  { id: 'oficina', name: 'Oficina', type: 'expense' },
  { id: 'other', name: 'Other', type: 'expense' }
];

export const MOCK_DRIVERS: Driver[] = [
  { id: 'd1', name: 'António Silva', phone: '9910001', license: 'C-12345', status: 'available', currentVehicleId: 'v2' },
  { id: 'd2', name: 'Pedro Gomes', phone: '9910002', license: 'C-67890', status: 'busy', currentVehicleId: 'v6' },
  { id: 'd3', name: 'Manuel Lopes', phone: '9910003', license: 'C-54321', status: 'off_duty' }
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    make: 'Toyota',
    model: 'Yaris',
    year: 2022,
    category: 'economy',
    transmission: 'manual',
    seats: 5,
    pricePerDay: 4500,
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    available: true,
    status: 'available',
    rating: 4.8,
    reviewCount: 12,
    plate: 'ST-22-AV',
    usageType: 'rental',
  },
  {
    id: 'v2',
    make: 'Renault',
    model: 'Duster',
    year: 2023,
    category: 'suv',
    transmission: 'manual',
    seats: 5,
    pricePerDay: 6500,
    image: 'https://images.unsplash.com/photo-1603577600377-160877990176?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    available: true,
    status: 'available',
    rating: 4.5,
    reviewCount: 8,
    plate: 'ST-45-XP',
    usageType: 'rental',
  },
  {
    id: 'v3',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2023,
    category: 'suv',
    transmission: 'automatic',
    seats: 5,
    pricePerDay: 8000,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    available: true,
    status: 'rented',
    rating: 4.9,
    reviewCount: 15,
    plate: 'ST-88-GT',
    usageType: 'rental',
  },
  {
    id: 'v4',
    make: 'Mitsubishi',
    model: 'L200',
    year: 2021,
    category: 'luxury',
    transmission: 'manual',
    seats: 5,
    pricePerDay: 9500,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    available: true,
    status: 'available',
    rating: 4.7,
    reviewCount: 22,
    plate: 'ST-10-TR',
    usageType: 'rental',
  },
  {
    id: 'v5',
    make: 'Toyota',
    model: 'Hiace',
    year: 2019,
    category: 'van',
    transmission: 'manual',
    seats: 15,
    pricePerDay: 10000,
    image: 'https://images.unsplash.com/photo-1632245889029-e41314275628?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    available: false,
    status: 'maintenance',
    rating: 4.2,
    reviewCount: 5,
    plate: 'ST-99-VN',
    usageType: 'rental',
  },
  {
    id: 'v6',
    make: 'Suzuki',
    model: 'Jimny',
    year: 2023,
    category: 'suv',
    transmission: 'manual',
    seats: 4,
    pricePerDay: 6000,
    image: 'https://images.unsplash.com/photo-1599908680199-31742469956f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    available: true,
    status: 'available',
    rating: 4.9,
    reviewCount: 30,
    plate: 'ST-33-JM',
    usageType: 'both',
  }
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'RES-001',
    vehicleId: 'v1',
    type: 'vehicle',
    userId: 'u1',
    customerName: 'Maria Santos',
    startDate: '2023-11-10',
    endDate: '2023-11-15',
    status: 'completed',
    total: 22500,
    pickupType: 'office',
    paymentStatus: 'paid',
    dateCreated: '2023-11-01',
    pickupLocation: 'airport',
    flightNumber: 'TP1535'
  },
  {
    id: 'RES-002',
    vehicleId: 'v3',
    type: 'vehicle',
    userId: 'u2',
    customerName: 'John Smith',
    startDate: '2023-12-01',
    endDate: '2023-12-05',
    status: 'active',
    total: 32000,
    pickupType: 'delivery',
    pickupAddress: 'Hotel Pestana Tropico',
    paymentStatus: 'paid',
    dateCreated: '2023-11-20',
    pickupLocation: 'custom'
  },
  {
    id: 'RES-003',
    vehicleId: 'v2',
    type: 'vehicle',
    userId: 'u3',
    customerName: 'Carlos Ferreira',
    startDate: '2023-12-20',
    endDate: '2023-12-27',
    status: 'confirmed',
    total: 45500,
    pickupType: 'office',
    paymentStatus: 'paid',
    dateCreated: '2023-12-05',
    pickupLocation: 'city'
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    vehicleId: 'v1',
    customerName: 'Maria Santos',
    rating: 5,
    comment: 'Carro muito económico e limpo. Recomendo!',
    date: '2023-11-16',
    status: 'approved'
  },
  {
    id: 'r2',
    vehicleId: 'v3',
    customerName: 'Peter Jones',
    rating: 4,
    comment: 'Great car for island roads, but pickup was slightly delayed.',
    date: '2023-10-05',
    status: 'approved'
  },
  {
    id: 'r3',
    vehicleId: 'v2',
    customerName: 'Ana Silva',
    rating: 5,
    comment: 'Serviço excelente da Auto Vicente.',
    date: '2023-12-01',
    status: 'pending'
  }
];

export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'e1',
    description: 'Mudança de óleo Yaris',
    amount: 5000,
    category: 'maintenance',
    date: '2023-11-05'
  },
  {
    id: 'e2',
    description: 'Combustível Fleet',
    amount: 12000,
    category: 'fuel',
    date: '2023-11-10'
  },
  {
    id: 'e3',
    description: 'Publicidade Facebook',
    amount: 3500,
    category: 'marketing',
    date: '2023-11-15'
  }
];

export const MOCK_TOURS: Tour[] = [
  {
    id: 't1',
    title: 'Volta à Ilha Completa',
    description: 'Um dia inteiro explorando o melhor de Santiago. Visite a Cidade Velha, o Jardim Botânico, o Tarrafal e a Serra Malagueta. Almoço incluído.',
    image: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    duration: '8 Horas',
    price: 12000,
    features: ['Almoço incluído', 'Guia certificado', 'Pickup no hotel', 'Entradas em museus'],
    capacity: 8
  },
  {
    id: 't2',
    title: 'Cidade Velha Histórica',
    description: 'Mergulhe na história de Cabo Verde com um passeio guiado pela primeira cidade construída pelos europeus nos trópicos. Património Mundial da UNESCO.',
    image: 'https://images.unsplash.com/photo-1582234057635-a505f0187424?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    duration: '4 Horas',
    price: 4500,
    features: ['Guia histórico', 'Visita à Fortaleza', 'Água incluída'],
    capacity: 15
  },
  {
    id: 't3',
    title: 'Aventura Serra Malagueta',
    description: 'Trekking no parque natural da Serra Malagueta. Vistas deslumbrantes e contato direto com a natureza endémica de Cabo Verde.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    duration: '6 Horas',
    price: 6000,
    features: ['Guia de montanha', 'Lanche incluído', 'Equipamento básico'],
    capacity: 6
  }
];

export const TRANSLATIONS: Record<string, Translation> = {
  pt: {
    nav: {
      home: 'Início',
      fleet: 'Frota',
      tours: 'Tours',
      admin: 'Administração',
      login: 'Entrar',
      logout: 'Sair',
      my_reservations: 'Minhas Reservas',
      welcome: 'Olá',
    },
    hero: {
      title: 'Alugue o carro perfeito para sua jornada',
      subtitle: 'Entrega em domicílio, preços transparentes e reservas simplificadas.',
      search_placeholder: 'Local de retirada (ex: Praia)',
      search_btn: 'Buscar Disponibilidade',
      pickup_date: 'Data Retirada',
      dropoff_date: 'Data Devolução',
      error_dates: 'Selecione datas válidas',
    },
    filters: {
      all: 'Todos',
      economy: 'Económico',
      suv: 'SUV',
      luxury: 'Luxo',
      automatic: 'Automático',
      manual: 'Manual',
      van: 'Van',
    },
    vehicle: {
      day: 'dia',
      seats: 'lugares',
      book_now: 'Reservar Agora',
      unavailable: 'Indisponível (Datas)',
      reviews: 'avaliações',
      maintenance: 'Manutenção',
    },
    booking: {
      title: 'Finalizar Reserva',
      step_details: 'Detalhes',
      step_extras: 'Extras',
      step_docs: 'Documentos',
      step_payment: 'Pagamento',
      total: 'Total',
      discount_applied: 'Desconto (>7 dias)',
      pay_now: 'A pagar agora (Depósito)',
      pay_later: 'A pagar ao balcão',
      delivery_opt: 'Receber em casa (+2000 CVE)',
      delivery_placeholder: 'Endereço de entrega...',
      upload_id: 'Carregar BI / Passaporte',
      upload_license: 'Carregar Carta de Condução',
      upload_success: 'Arquivo recebido',
      confirm_pay: 'Pagar e Confirmar',
      payment_method: 'Método de Pagamento',
      pay_vinti4: 'Rede Vinti4 (Débito Local)',
      pay_card: 'Cartão de Crédito (Genérico)',
      pay_stripe: 'Cartão de Crédito (Stripe)',
      pay_paypal: 'PayPal',
      success_title: 'Reserva Confirmada!',
      success_msg: 'Seu pagamento foi processado com sucesso.',
      download_contract: 'Baixar Contrato',
      close: 'Fechar',
      reviews_title: 'Avaliações',
      no_reviews: 'Sem avaliações.',
      write_review: 'Avaliar',
      submit_review: 'Enviar',
      your_rating: 'Sua Nota',
      your_comment: 'Comentário',
      extras_title: 'Adicionar Extras',
      extra_gps: 'GPS (+500/dia)',
      extra_child_seat: 'Cadeira Criança (+1000/dia)',
      extra_insurance: 'Seguro Total (+2500/dia)',
      error_dates_invalid: 'Data final deve ser após data inicial',
      about_company_title: 'Sobre esta empresa',
      about_company_desc: 'Ao reservar conosco está a suportar o comércio local de Cabo Verde.',
      useful_info_title: 'Informação útil',
      info_cancellation: 'Cancelamento gratuito até 24h',
      info_no_credit_card: 'Não é necessário cartão de crédito',
      info_insurance: 'Cobertura de danos com franquia (CDW)',
      info_deposit: 'Caução no levantamento',
      pickup_location_title: 'Ponto de levantamento',
      loc_airport: 'Aeroporto (RAI)',
      loc_city: 'Escritório Centro Cidade',
      loc_port: 'Terminal Marítimo',
      loc_custom: 'Outra Localização',
      free: 'Grátis',
      flight_number: 'Número do Voo',
      flight_hint: 'Se o voo atrasar, saberemos.',
      num_passengers: 'Número de pessoas',
      payment_processing: 'Processando pagamento...',
      payment_success: 'Pagamento aprovado!',
      card_holder: 'Nome no Cartão',
      card_number: 'Número do Cartão',
      card_expiry: 'Validade (MM/AA)',
      card_cvc: 'CVC',
      vinti4_phone: 'Telemóvel (ex: 9911234)',
      vinti4_instr: 'Você receberá uma notificação no seu telemóvel para confirmar o pagamento.',
      stripe_instr: 'Pagamento seguro processado via Stripe.',
      paypal_instr: 'Você será redirecionado para o PayPal para completar sua compra.',
    },
    tour_booking: {
      title: 'Comprar Pacote de Tour',
      select_date: 'Data do Passeio',
      guests: 'Número de Pessoas',
      total_price: 'Preço Total',
      confirm_purchase: 'Confirmar Compra',
      success_title: 'Compra Realizada com Sucesso!',
      success_msg: 'Seu tour foi agendado. Prepare-se para a aventura!',
      email_sent: 'Um e-mail de confirmação foi enviado para',
      download_ticket: 'Baixar Voucher',
    },
    tours: {
      title: 'Experiências em Santiago',
      subtitle: 'Descubra a ilha com nossos pacotes exclusivos com motorista ou self-drive.',
      book_tour: 'Ver Frota Disponível',
      duration: 'Duração',
      included: 'Inclui',
      view_details: 'Ver Detalhes',
      buy_now: 'Comprar Pacote',
    },
    admin: {
      dashboard: 'Painel Admin',
      revenue: 'Receita Mensal',
      active_rentals: 'Em Circulação',
      fleet_status: 'Status da Frota',
      recent_reservations: 'Reservas Recentes',
      reviews_moderation: 'Moderação',
      approve: 'Aprovar',
      reject: 'Rejeitar',
      status: 'Status',
      tabs_overview: 'Visão Geral',
      tabs_fleet: 'Frota',
      tabs_reservations: 'Reservas',
      tabs_deliveries: 'Entregas',
      tabs_reviews: 'Avaliações',
      tabs_settings: 'Configurações',
      tabs_finance: 'Financeiro',
      tabs_tours: 'Tours',
      tabs_reports: 'Relatórios',
      tabs_taxi: 'Táxis',
      filter_pending: 'Pendentes',
      filter_all: 'Todos',
      add_vehicle: 'Adicionar Veículo',
      add_tour: 'Adicionar Tour',
      edit: 'Editar',
      delete: 'Excluir',
      plate: 'Matrícula',
      price: 'Preço/Dia',
      actions: 'Ações',
      save: 'Salvar',
      cancel: 'Cancelar',
      mark_active: 'Entregar (Check-out)',
      mark_completed: 'Devolver (Check-in)',
      mark_cancelled: 'Cancelar',
      confirm: 'Confirmar',
      confirm_delete: 'Tem certeza que deseja excluir este veículo?',
      api_key_label: 'Chave da API Geral (Mapas, etc)',
      api_key_placeholder: 'Insira sua chave de API aqui...',
      vinti4_section: 'Integração Rede Vinti4',
      vinti4_pos_id: 'ID do POS (Vinti4)',
      vinti4_api_key: 'Token de Autenticação (Vinti4)',
      vinti4_doc_link: 'Ver documentação oficial Vinti4',
      stripe_section: 'Integração Stripe',
      stripe_key: 'Chave Pública (Publishable Key)',
      paypal_section: 'Integração PayPal',
      paypal_client: 'Client ID',
      save_settings: 'Salvar Configurações',
      settings_saved: 'Configurações salvas com sucesso!',
      payment_status: 'Pagamento',
      paid: 'Pago',
      pending_payment: 'Pendente',
      fin_total_income: 'Receita Total',
      fin_total_expenses: 'Despesas Totais',
      fin_net_profit: 'Lucro Líquido',
      fin_add_expense: 'Nova Despesa',
      fin_desc: 'Descrição',
      fin_amount: 'Valor (CVE)',
      fin_category: 'Categoria',
      fin_date: 'Data',
      fin_recent_transactions: 'Transações Recentes',
      fin_type_income: 'Receita (Reserva)',
      fin_type_expense: 'Despesa',
      // Settings sub-tabs
      settings_general: 'Dados da Empresa',
      settings_integrations: 'Integrações',
      settings_payments: 'Pagamentos',
      settings_categories: 'Categorias',
      cat_vehicle: 'Categorias de Veículos',
      cat_expense: 'Categorias de Despesas',
      cat_add: 'Nova Categoria',
      cat_name: 'Nome da Categoria',
      cat_add_btn: 'Adicionar',
      comp_name: 'Nome da Empresa',
      comp_email: 'Email de Contato',
      comp_phone: 'Telefone',
      comp_address: 'Endereço Físico',
      // Tours
      tour_title: 'Título',
      tour_price: 'Preço',
      tour_features: 'Destaques',
      tour_features_help: 'Separados por vírgula',
      // Reports
      rep_occupancy: 'Taxa de Ocupação',
      rep_avg_ticket: 'Ticket Médio',
      rep_rev_by_cat: 'Receita por Categoria',
      rep_monthly_growth: 'Crescimento Mensal',
      rep_export_csv: 'Exportar CSV',
      rep_export_pdf: 'Exportar PDF',
      rep_statement: 'Demonstrativo Financeiro (DRE)',
      rep_avg_duration: 'Duração Média (Dias)',
      rep_days_rented: 'Total Dias Alugados',
      rep_status_dist: 'Distribuição por Status',
      rep_vehicle_perf: 'Desempenho da Frota',
      rep_top_vehicles: 'Top 5 Veículos (Receita)',
      rep_perf_days: 'Dias Alugados',
      rep_perf_revenue: 'Receita Total',
      // Advanced Reports
      rep_net_margin: 'Margem Líquida',
      rep_revpar: 'RevPAR (Receita/Carro)',
      rep_maint_cost: 'Custo de Manutenção',
      rep_pickup_dist: 'Locais de Entrega',
      rep_lead_time: 'Lead Time Médio (Dias)',
      // Filters
      rep_filter_date_start: 'Data Início',
      rep_filter_date_end: 'Data Fim',
      rep_filter_vehicle: 'Veículo',
      rep_filter_category: 'Categoria',
      rep_filter_type: 'Tipo de Transação',
      rep_filter_clear: 'Limpar Filtros',
      rep_filter_apply: 'Aplicar',
      rep_quick_7days: 'Últimos 7 dias',
      rep_quick_month: 'Este Mês',
      rep_quick_year: 'Este Ano',
      // Enhanced Overview
      ov_today_pickups: 'Levantamentos Hoje',
      ov_today_returns: 'Devoluções Hoje',
      ov_occupancy_rate: 'Ocupação Atual',
      ov_fleet_health: 'Saúde da Frota',
      ov_action_needed: 'Atenção Necessária',
      ov_revenue_trend: 'Tendência de Receita',
      ov_growth_mom: 'Cresc. Mensal',
      ov_pending_actions: 'Ações Pendentes',
      fleet_status_cleaning: 'Cleaning (Buffer)',
      search_placeholder_res: 'Search name or ID...',
      search_placeholder_fleet: 'Plate or Model...',
      filter_status_label: 'Filter Status',
      taxi_settlement: 'Fecho de Caixa (Diária)',
      taxi_daily_total: 'Total do Dia',
      taxi_driver_status: 'Status dos Motoristas',
      taxi_amount_paid: 'Valor Entregue',
      taxi_register_payment: 'Registrar Pagamento',
      taxi_paid: 'Pago',
      taxi_unpaid: 'Pendente',
      taxi_history: 'Histórico Recente',
      taxi_tab_operations: 'Operações Diárias',
      taxi_tab_drivers: 'Gestão de Motoristas',
      taxi_tab_vehicles: 'Viaturas',
      taxi_add_driver: 'Novo Motorista',
      taxi_driver_name: 'Nome Completo',
      taxi_driver_license: 'Número da Carta',
      taxi_driver_phone: 'Telemóvel',
      taxi_assign_vehicle: 'Vincular Viatura',
      fleet_usage_type: 'Tipo de Uso',
      fleet_usage_rental: 'Aluguer',
      fleet_usage_taxi: 'Táxi',
      fleet_usage_both: 'Ambos',
    },
    customer: {
      dashboard: 'Minhas Reservas',
      status: 'Status',
      leave_review: 'Avaliar',
      review_submitted: 'Enviada',
      download_contract: 'Contrato',
      cancel_booking: 'Cancelar',
      confirm_cancel: 'Tem certeza que deseja cancelar esta reserva? (Grátis se faltar mais de 48h)',
      tabs_reservations: 'Minhas Reservas',
      tabs_profile: 'Configurações de Perfil',
      profile_settings: 'Editar Perfil',
      personal_details: 'Dados Pessoais',
      save_changes: 'Salvar Alterações',
      profile_updated: 'Perfil atualizado com sucesso!',
    },
    auth: {
      login_title: 'Acessar Conta',
      login_admin: 'Entrar como Admin',
      login_customer: 'Entrar como Cliente',
      email: 'Email',
      password: 'Senha',
    },
    footer: {
      about: 'Sobre Nós',
      about_text: 'A Auto Vicente oferece a melhor experiência de aluguel de carros em Cabo Verde. Segurança, conforto e suporte 24h.',
      links: 'Links Rápidos',
      contact: 'Contacto',
      address: 'Achada Santo António, Praia, Cabo Verde',
      phone: '+238 991 12 34',
      email: 'reservas@autovicente.cv',
      rights: 'Todos os direitos reservados.',
      privacy: 'Privacidade',
      terms: 'Termos',
    },
    pagination: {
      prev: 'Anterior',
      next: 'Próximo',
      page: 'Página',
      of: 'de',
    },
  },
  en: {
    nav: {
      home: 'Home',
      fleet: 'Fleet',
      tours: 'Tours',
      admin: 'Admin',
      login: 'Login',
      logout: 'Logout',
      my_reservations: 'My Reservations',
      welcome: 'Hello',
    },
    hero: {
      title: 'Rent the perfect car for your journey',
      subtitle: 'Home delivery, transparent pricing, and simple booking.',
      search_placeholder: 'Pickup location (e.g. Praia)',
      search_btn: 'Search Availability',
      pickup_date: 'Pickup Date',
      dropoff_date: 'Dropoff Date',
      error_dates: 'Select valid dates',
    },
    filters: {
      all: 'All',
      economy: 'Economy',
      suv: 'SUV',
      luxury: 'Luxury',
      automatic: 'Automatic',
      manual: 'Manual',
      van: 'Van',
    },
    vehicle: {
      day: 'day',
      seats: 'seats',
      book_now: 'Book Now',
      unavailable: 'Unavailable (Dates)',
      reviews: 'reviews',
      maintenance: 'Maintenance',
    },
    booking: {
      title: 'Complete Reservation',
      step_details: 'Details',
      step_extras: 'Extras',
      step_docs: 'Documents',
      step_payment: 'Payment',
      total: 'Total Amount',
      discount_applied: 'Discount (>7 days)',
      pay_now: 'Pay Now (Deposit)',
      pay_later: 'Pay at Counter',
      delivery_opt: 'Deliver to location (+2000 CVE)',
      delivery_placeholder: 'Delivery address...',
      upload_id: 'Upload ID / Passport',
      upload_license: 'Upload Driver License',
      upload_success: 'File received',
      confirm_pay: 'Pay & Confirm',
      payment_method: 'Payment Method',
      pay_vinti4: 'Vinti4 Network (Local Debit)',
      pay_card: 'Credit Card (Generic)',
      pay_stripe: 'Credit Card (Stripe)',
      pay_paypal: 'PayPal',
      success_title: 'Reservation Confirmed!',
      success_msg: 'Your payment was processed successfully.',
      download_contract: 'Download Contract',
      close: 'Close',
      reviews_title: 'Reviews',
      no_reviews: 'No reviews yet.',
      write_review: 'Rate Vehicle',
      submit_review: 'Submit Review',
      your_rating: 'Your Rating',
      your_comment: 'Your Comment',
      extras_title: 'Add Extras',
      extra_gps: 'GPS (+500/day)',
      extra_child_seat: 'Child Seat (+1000/day)',
      extra_insurance: 'Full Insurance (+2500/day)',
      error_dates_invalid: 'End date must be after start date',
      about_company_title: 'About this company',
      about_company_desc: 'By booking with us you are supporting local Cape Verdean commerce.',
      useful_info_title: 'Useful Information',
      info_cancellation: 'Free cancellation up to 24h',
      info_no_credit_card: 'No credit card required',
      info_insurance: 'Damage coverage with deductible (CDW)',
      info_deposit: 'Security deposit on pickup',
      pickup_location_title: 'Pickup Location',
      loc_airport: 'Airport (RAI)',
      loc_city: 'City Center Office',
      loc_port: 'Maritime Terminal',
      loc_custom: 'Other Location',
      free: 'Free',
      flight_number: 'Flight Number',
      flight_hint: 'So we know if your flight is delayed.',
      num_passengers: 'Number of people',
      payment_processing: 'Processing payment...',
      payment_success: 'Payment approved!',
      card_holder: 'Cardholder Name',
      card_number: 'Card Number',
      card_expiry: 'Expiry (MM/YY)',
      card_cvc: 'CVC',
      vinti4_phone: 'Mobile Number (e.g. 9911234)',
      vinti4_instr: 'You will receive a push notification on your phone to confirm the payment.',
      stripe_instr: 'Secure payment processed via Stripe.',
      paypal_instr: 'You will be redirected to PayPal to complete your purchase.',
    },
    tour_booking: {
      title: 'Buy Tour Package',
      select_date: 'Tour Date',
      guests: 'Number of Guests',
      total_price: 'Total Price',
      confirm_purchase: 'Confirm Purchase',
      success_title: 'Purchase Successful!',
      success_msg: 'Your tour has been scheduled. Get ready for the adventure!',
      email_sent: 'A confirmation email has been sent to',
      download_ticket: 'Download Voucher',
    },
    tours: {
      title: 'Santiago Experiences',
      subtitle: 'Discover the island with our exclusive driver or self-drive packages.',
      book_tour: 'See Available Fleet',
      duration: 'Duration',
      included: 'Included',
      view_details: 'View Details',
      buy_now: 'Buy Package',
    },
    admin: {
      dashboard: 'Dashboard',
      revenue: 'Monthly Revenue',
      active_rentals: 'On Road',
      fleet_status: 'Fleet Status',
      recent_reservations: 'Recent Reservations',
      reviews_moderation: 'Review Moderation',
      approve: 'Approve',
      reject: 'Reject',
      status: 'Status',
      tabs_overview: 'Overview',
      tabs_fleet: 'Fleet Management',
      tabs_reservations: 'Reservations',
      tabs_deliveries: 'Deliveries',
      tabs_reviews: 'Reviews',
      tabs_settings: 'Settings',
      tabs_finance: 'Finance',
      tabs_tours: 'Tours',
      tabs_reports: 'Reports',
      tabs_taxi: 'Taxi', // NEW
      filter_pending: 'Pending',
      filter_all: 'All',
      add_vehicle: 'Add Vehicle',
      add_tour: 'Add Tour',
      edit: 'Edit',
      delete: 'Delete',
      plate: 'Plate',
      price: 'Price/Day',
      actions: 'Actions',
      save: 'Save',
      cancel: 'Cancel',
      mark_active: 'Dispatch (Check-out)',
      mark_completed: 'Return (Check-in)',
      mark_cancelled: 'Cancel',
      confirm: 'Confirm',
      confirm_delete: 'Are you sure you want to delete this vehicle?',
      api_key_label: 'General API Key (Maps, etc)',
      api_key_placeholder: 'Enter your API key here...',
      vinti4_section: 'Vinti4 Network Integration',
      vinti4_pos_id: 'POS ID (Vinti4)',
      vinti4_api_key: 'Authentication Token (Vinti4)',
      vinti4_doc_link: 'View official Vinti4 documentation',
      stripe_section: 'Stripe Integration',
      stripe_key: 'Public Key (Publishable Key)',
      paypal_section: 'PayPal Integration',
      paypal_client: 'Client ID',
      save_settings: 'Save Settings',
      settings_saved: 'Settings saved successfully!',
      payment_status: 'Payment',
      paid: 'Paid',
      pending_payment: 'Pending',
      fin_total_income: 'Total Revenue',
      fin_total_expenses: 'Total Expenses',
      fin_net_profit: 'Net Profit',
      fin_add_expense: 'Add Expense',
      fin_desc: 'Description',
      fin_amount: 'Amount (CVE)',
      fin_category: 'Category',
      fin_date: 'Date',
      fin_recent_transactions: 'Recent Transactions',
      fin_type_income: 'Income (Reservation)',
      fin_type_expense: 'Expense',
      // Settings sub-tabs
      settings_general: 'Company Details',
      settings_integrations: 'Integrations',
      settings_payments: 'Payments',
      settings_categories: 'Categories',
      cat_vehicle: 'Vehicle Categories',
      cat_expense: 'Expense Categories',
      cat_add: 'New Category',
      cat_name: 'Category Name',
      cat_add_btn: 'Add',
      comp_name: 'Company Name',
      comp_email: 'Contact Email',
      comp_phone: 'Phone Number',
      comp_address: 'Physical Address',
      // Tours
      tour_title: 'Title',
      tour_price: 'Price',
      tour_features: 'Features',
      tour_features_help: 'Comma separated',
      // Reports
      rep_occupancy: 'Occupancy Rate',
      rep_avg_ticket: 'Average Ticket',
      rep_rev_by_cat: 'Revenue by Category',
      rep_monthly_growth: 'Monthly Growth',
      rep_export_csv: 'Export CSV',
      rep_export_pdf: 'Export PDF',
      rep_statement: 'Financial Statement',
      rep_avg_duration: 'Avg Duration (Days)',
      rep_days_rented: 'Total Days Rented',
      rep_status_dist: 'Status Distribution',
      rep_vehicle_perf: 'Fleet Performance',
      rep_top_vehicles: 'Top 5 Vehicles (Revenue)',
      rep_perf_days: 'Days Rented',
      rep_perf_revenue: 'Total Revenue',
      // Advanced Reports
      rep_net_margin: 'Net Margin (%)',
      rep_revpar: 'RevPAR (Rev/Car)',
      rep_maint_cost: 'Maintenance Cost',
      rep_pickup_dist: 'Pickup Location Dist.',
      rep_lead_time: 'Avg Lead Time (Days)',
      // Filters
      rep_filter_date_start: 'Start Date',
      rep_filter_date_end: 'End Date',
      rep_filter_vehicle: 'Vehicle',
      rep_filter_category: 'Category',
      rep_filter_type: 'Transaction Type',
      rep_filter_clear: 'Clear Filters',
      rep_filter_apply: 'Apply',
      rep_quick_7days: 'Last 7 Days',
      rep_quick_month: 'This Month',
      rep_quick_year: 'This Year',
      // Enhanced Overview
      ov_today_pickups: 'Pickups Today',
      ov_today_returns: 'Returns Today',
      ov_occupancy_rate: 'Current Occupancy',
      ov_fleet_health: 'Fleet Health',
      ov_action_needed: 'Action Needed',
      ov_revenue_trend: 'Revenue Trend',
      ov_growth_mom: 'MoM Growth',
      ov_pending_actions: 'Pending Actions',
      fleet_status_cleaning: 'Cleaning (Buffer)',
      search_placeholder_res: 'Search name or ID...',
      search_placeholder_fleet: 'Plate or Model...',
      filter_status_label: 'Filter Status',
      taxi_settlement: 'Daily Settlement',
      taxi_daily_total: 'Today\'s Total',
      taxi_driver_status: 'Driver Status',
      taxi_amount_paid: 'Amount Paid',
      taxi_register_payment: 'Register Payment',
      taxi_paid: 'Paid',
      taxi_unpaid: 'Pending',
      taxi_history: 'Recent History',
      taxi_tab_operations: 'Daily Operations',
      taxi_tab_drivers: 'Driver Management',
      taxi_tab_vehicles: 'Vehicles',
      taxi_add_driver: 'Add New Driver',
      taxi_driver_name: 'Full Name',
      taxi_driver_license: 'License Number',
      taxi_driver_phone: 'Phone Number',
      taxi_assign_vehicle: 'Assign Vehicle',
      fleet_usage_type: 'Usage Type',
      fleet_usage_rental: 'Rental',
      fleet_usage_taxi: 'Taxi',
      fleet_usage_both: 'Both',
    },
    customer: {
      dashboard: 'My Reservations',
      status: 'Status',
      leave_review: 'Leave a Review',
      review_submitted: 'Review Submitted',
      download_contract: 'Contract',
      cancel_booking: 'Cancel Booking',
      confirm_cancel: 'Are you sure you want to cancel this reservation? (Free cancellation if >48h)',
      tabs_reservations: 'My Reservations',
      tabs_profile: 'Profile Settings',
      profile_settings: 'Edit Profile',
      personal_details: 'Personal Details',
      save_changes: 'Save Changes',
      profile_updated: 'Profile updated successfully!',
    },
    auth: {
      login_title: 'Login',
      login_admin: 'Login as Admin',
      login_customer: 'Login as Customer',
      email: 'Email',
      password: 'Password',
    },
    footer: {
      about: 'About Us',
      about_text: 'Auto Vicente offers the best car rental experience in Cape Verde. Safety, comfort and 24h support.',
      links: 'Quick Links',
      contact: 'Contact',
      address: 'Achada Santo António, Praia, Cape Verde',
      phone: '+238 991 12 34',
      email: 'reservas@autovicente.cv',
      rights: 'All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
    },
    pagination: {
      prev: 'Previous',
      next: 'Next',
      page: 'Page',
      of: 'of',
    },
  },
};